### ISSUE TITLE
Fails to find needle when needle is prefixed with partial match

### ISSUE THREAD

**Issue by limulus** [soldair/node-buffer-indexof#2]
This doesn’t happen to affect my usage of buffer-indexof, but I discovered this while reading through the code. You can see the issue when running the following in the Node REPL:

```javascript
var bufferIndexOf = require("buffer-indexof")
"aaba".indexOf("ab")  // --> 1
bufferIndexOf(new Buffer("aaba"), new Buffer("ab"))  // --> -1
```

I suppose the easiest thing to do would be to update the README to indicate that this implementation is only reliable for finding single-byte needles. :)

**Comment by soldair** [comment]
i think it should be good at finding other needles. thanks for the issue!

**Comment by soldair** [comment]
fixed! thanks for finding this.
published to npm @ version 1.0.0

**Comment by bahaa-aidi** [comment]
not fixed! consider this example:
```javascript
'aaaba'.indexOf('aaba') // --> 1
bufferIndexOf(new Buffer('aaaba'), new Buffer('aaba')) // --> -1
```
just looking at the complexity of the algorithm gives you a feeling it can't be correct.
`let n = haystack.length, m = needle.length`
the complexity of your algorithm is `O(n)` time and `O(1)` space while the complexity of advanced  string searching algorithms like [Knuth–Morris–Pratt algorithm](https://en.wikipedia.org/wiki/Knuth%E2%80%93Morris%E2%80%93Pratt_algorithm) and [Boyer–Moore  algorithm](https://en.wikipedia.org/wiki/Boyer%E2%80%93Moore_string_search_algorithm) is `O(n+m)` time and `O(m)` space.
the problem is when you find a mismatch (at index 3 in this example) you reset the search from that index ignoring that the match could start in indexes already skipped in the partial match (1 and 2 in this example).
see [String searching algorithm](https://en.wikipedia.org/wiki/String_searching_algorithm) for more information.

**Comment by soldair** [comment]
thanks! feel free to make a pull request should be simple enough to reset the index appropriately.

otherwise ill get to it soon =)
